.PHONY: clean All

All:
	@echo "----------Building project:[ readfile - Debug ]----------"
	@cd "readfile" && "$(MAKE)" -f  "readfile.mk"
clean:
	@echo "----------Cleaning project:[ readfile - Debug ]----------"
	@cd "readfile" && "$(MAKE)" -f  "readfile.mk" clean
