.PHONY: clean All

All:
	@echo "----------Building project:[ square - Debug ]----------"
	@cd "square" && "$(MAKE)" -f  "square.mk"
clean:
	@echo "----------Cleaning project:[ square - Debug ]----------"
	@cd "square" && "$(MAKE)" -f  "square.mk" clean
